apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-config
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"
      index-version = "tsi1"
      wal-fsync-delay = "50ms"
      cache-snapshot-memory-size = "100m"
      cache-max-memory-size = "2g"
      max-values-per-tag = 0
      max-series-per-database = 0
      max-index-log-file-size = "100m"
      cache-snapshot-write-cold-duration = "30m"
      compact-throughput = "16m"
      compact-throughput-burst = "16m"

    [monitor]
      store-enabled = false