apiVersion: v1
kind: Service
metadata: 
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
    {{- if (eq "NodePort" .Values.service.type) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ .Chart.Name }}
