clickhouse:
  ##
  ## The instance number of Clickhouse
  replicas: "1"
  ## Clickhouse image configuration.
  image: "clickhouse/clickhouse-server"
  imageVersion: "22.3"
  imagePullPolicy: "IfNotPresent"  
  resource:
    request:
      cpu: 4
      memory: 16384Mi
    limit:
      cpu: 4
      memory: 16384Mi
  #imagePullSecrets: 
  ## Periodic probe of container liveness. Container will be restarted if the probe fails. Cannot be updated. 
  ## More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
  livenessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  ## Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails. Cannot be updated. 
  ## More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
  readinessProbe:
    enabled: true
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"
  ##
  ## Clickhouse service configuration.
  service_type: "NodePort"
  ##
  ## The port for connecting to the server over HTTP
  http_port: "8123"
  http_node_port: "30123"
  ##
  ## Port for communicating with clients over the TCP protocol.
  tcp_port: "9000"
  tcp_node_port: "30090"
  ##
  ## Port for exchanging data between ClickHouse servers.
  interserver_http_port: "9009"
  interserver_http_node_port: "30099"