global:
  namespace: default

app:
  env:
    database: test
    password: 123456
  image:
    pullPolicy: IfNotPresent
    registry: mysql
    version: 5.7.39
  resource:
    request:
      cpu: 4
      memory: 16384Mi
    limit:
      cpu: 4
      memory: 16384Mi

service:
  nodePort: 30336
  type: NodePort